#  Superstore Sales Analysis
### End-to-End Data Analysis Project
---
> **Tools Used:** Python · Pandas · NumPy · Matplotlib · Seaborn · SQL · Power BI  
> **Dataset:** Superstore Sales Dataset — 9,994 US retail orders (2014–2017)  
> **Author:** Abdullah  Waseem

> **Date:** June 2025  

---

## Project Overview

This project is a complete end-to-end data analysis of the **Superstore Sales Dataset** —
a retail company operating across the United States. The analysis covers 4 years of
transactional data (2014–2017) containing information about orders, customers, products,
and financials.

The goal is to answer **39 real business questions** across 7 categories and deliver
actionable insights that help the business:

- Identify profitable and unprofitable areas
- Understand customer behavior and segmentation
- Optimize discount and pricing strategy
- Improve regional and operational performance
- Plan for seasonal trends and growth

---

##  Project Structure

This analysis is divided into 4 notebooks:

| Notebook | Description |
|---|---|
| `01_data_understanding.ipynb` | Load dataset, inspect structure, understand columns and data quality |
| `02_data_cleaning.ipynb` | Fix data types, handle missing values, standardize columns |
| `03_eda.ipynb` | Exploratory Data Analysis — distributions, correlations, patterns |
| `04_business_analysis.ipynb` | Answer all 39 business questions with analysis and visualizations |

---

## Business Questions

This project answers **39 business questions** across 7 categories:

| # | Category | Questions |
|---|---|---|
| 1 | Overall Business Performance | 5 questions |
| 2 | Regional Performance | 6 questions |
| 3 | Product & Category Analysis | 7 questions |
| 4 | Customer Analysis | 6 questions |
| 5 | Discount & Profitability | 5 questions |
| 6 | Shipping & Operations | 5 questions |
| 7 | Time Series & Trends | 5 questions |

---

## This Notebook — Data Understanding

**Objective:** Understand the dataset completely before any cleaning or analysis.

**In this notebook we will:**
- Load the raw dataset
- Inspect shape, columns, and data types
- Check for missing values and duplicates
- Understand unique values in categorical columns
- Review the date range and financial overview
- Document key observations for the cleaning phase

**Output:** A clear understanding of data quality issues and structure
that will guide the cleaning process in Notebook 2.

---

## 1: Environment Setup & Data Loading

Before any analysis we set up our working environment by:
- Mounting Google Drive to access the dataset
- Importing all required libraries
- Configuring display settings for clean output
- Loading the dataset into a Pandas DataFrame

> **Why this step matters:** A clean, consistent environment ensures
> our analysis runs without errors and outputs are readable throughout the notebook.
---

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:.2f}")

df = pd.read_excel("/content/drive/MyDrive/Superstore-Analysis/superstore.xlsx")

print(f"Dataset loaded: {df.shape[0]:,} rows × {df.shape[1]} columns")

Dataset loaded: 8,399 rows × 23 columns

##2: First Look at the Dataset <a id='2'></a>

Now that the data is loaded we inspect it from every angle before
touching anything.

**In this step we will check:**
- Column names and what each column represents
- Data types of each column
- Basic statistical summary
- Missing values
- Duplicate rows
- Unique values in categorical columns
- Date range covered by the dataset
- High level financial overview

> **Rule:** No cleaning, no analysis, no charts in this notebook.
> Observation only.
---

In [ ]:
print("Column Names:")
print("-" * 40)
for i, col in enumerate(df.columns, 1):
    print(f"{i:2}. {col}")

Column Names:
----------------------------------------
 1. Row ID
 2. Order ID
 3. Order Date
 4. Order Priority
 5. Order Quantity
 6. Sales
 7. Discount
 8. Ship Mode
 9. Profit
10. Unit Price
11. Shipping Cost
12. Customer Name
13. City
14. Zip Code
15. State
16. Region
17. Customer Segment
18. Product Category
19. Product Sub-Category
20. Product Name
21. Product Container
22. Product Base Margin
23. Ship Date

### 2.1 — First Look at the Data

#####Here we preview the first and last few rows of the dataset to understand what one row represents and what the data actually looks like at a glance.
---

In [ ]:
print(f"First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,Shipping Cost,Customer Name,City,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.54,0.04,Regular Air,-213.25,38.94,35.00,Muhammed MacIntyre,Highland Park,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.93,0.01,Regular Air,-4.64,2.08,2.56,Ruben Dartt,Edmonds,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
2,3,32,2011-07-15,High,26,2808.08,0.07,Regular Air,1054.82,107.53,5.81,Liz Pelletier,Elk Plain,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
3,4,32,2011-07-15,High,24,1761.40,0.09,Delivery Truck,-1748.56,70.89,89.30,Liz Pelletier,Elk Plain,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
4,5,32,2011-07-15,High,23,160.23,0.04,Regular Air,-85.13,7.99,5.03,Liz Pelletier,Elk Plain,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17

In [ ]:
print(f"Last 5 rows of the dataset:")
df.tail()

Last 5 rows of the dataset:

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,Shipping Cost,Customer Name,City,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
8394,8395,59971,2011-05-31,Critical,26,437.77,0.01,Express Air,-125.80,15.98,8.99,Brad Thomas,Manhattan Beach,90266,California,West,Home Office,Technology,Computer Peripherals,"Imation 3.5"" DS/HD IBM Formatted Diskettes, 50...",Small Pack,0.64,2011-06-02
8395,8396,59971,2011-05-31,Critical,45,514.86,0.08,Regular Air,-10.84,12.28,6.47,Brad Thomas,Manhattan Beach,90266,California,West,Home Office,Office Supplies,Paper,Xerox 1881,Small Box,0.38,2011-06-02
8396,8397,59971,2011-05-31,Critical,12,356.27,0.10,Express Air,84.53,30.98,5.09,Brad Thomas,Manhattan Beach,90266,California,West,Home Office,Office Supplies,Paper,Xerox 19,Small Box,0.40,2011-06-02
8397,8398,59973,2011-11-15,Low,29,11039.75,0.06,Delivery Truck,2148.97,400.97,14.70,Suzanne McNair,Slidell,70458,Louisiana,South,Small Business,Technology,Office Machines,Epson FX-980 Dot Matrix Printer,Jumbo Drum,0.59,2011-11-15
8398,8399,59973,2011-11-15,Low,30,4982.94,0.07,Delivery Truck,693.69,217.85,29.10,Suzanne McNair,Slidell,70458,Louisiana,South,Small Business,Furniture,Tables,Chromcraft Bull-Nose Wood Round Conference Tab...,Jumbo Box,0.68,2011-11-19

###  2.2 — Data Types

#####Checking the data type of every column. This is critical because Order Date and Ship Date must be datetime — not string — for any time-based analysis to work correctly.
---

In [ ]:
print("Data Types of Each Column:")
print("-" * 40)
print(df.dtypes)

Data Types of Each Column:
----------------------------------------
Row ID                           int64
Order ID                         int64
Order Date              datetime64[ns]
Order Priority                  object
Order Quantity                   int64
Sales                          float64
Discount                       float64
Ship Mode                       object
Profit                         float64
Unit Price                     float64
Shipping Cost                  float64
Customer Name                   object
City                            object
Zip Code                         int64
State                           object
Region                          object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Name                    object
Product Container               object
Product Base Margin            float64
Ship Date               datetime64[ns]
dtype: object

###  2.3 — Basic Statistical Summary

#####A statistical summary of all numeric columns showing count, mean, standard deviation, min, max and quartile values. This gives us an instant overview of the range and distribution of key financial columns.
---

In [ ]:
print("Statistical Summary of Numeric Columns:")
df.describe()

Statistical Summary of Numeric Columns:

,Row ID,Order ID,Order Date,Order Quantity,Sales,Discount,Profit,Unit Price,Shipping Cost,Zip Code,Product Base Margin,Ship Date
count,8399.00,8399.00,8399,8399.00,8399.00,8399.00,8399.00,8399.00,8399.00,8399.00,8336.00,8399
mean,4200.00,29965.18,2010-12-25 00:40:58.578402048,25.57,1775.88,0.05,181.18,89.35,12.84,52839.14,0.51,2010-12-27 01:28:48.634361088
min,1.00,3.00,2009-01-01 00:00:00,1.00,2.24,0.00,-14140.70,0.99,0.49,1001.00,0.35,2009-01-02 00:00:00
25%,2100.50,15011.50,2009-12-20 00:00:00,13.00,143.19,0.02,-83.31,6.48,3.30,30337.00,0.38,2009-12-22 12:00:00
50%,4200.00,29857.00,2010-12-17 00:00:00,26.00,449.42,0.05,-1.50,20.99,6.07,52732.00,0.52,2010-12-18 00:00:00
75%,6299.50,44596.00,2012-01-01 12:00:00,38.00,1709.32,0.08,162.75,85.99,13.99,77577.00,0.59,2012-01-03 12:00:00
max,8399.00,59973.00,2012-12-30 00:00:00,50.00,89061.05,0.25,27220.69,6783.02,164.73,99362.00,0.85,2012-12-30 00:00:00
std,2424.73,17260.88,NaN,14.48,3585.05,0.03,1196.65,290.35,17.26,28509.54,0.14,NaN

###  2.4 — Missing Values

#####Identifying columns with missing data and what percentage of that column is missing. Missing values must be handled before any analysis otherwise calculations will be incorrect.
---

In [ ]:
print("missing Values Analysis")
print("-" * 40)

missing_count = df.isna().sum()
missing_pct = (missing_count/ len(df)) * 100

missing_df = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing %": missing_pct.round(2)
})

missing_with_data = missing_df[missing_df["Missing Count"] > 0]

if len(missing_with_data) == 0:
  print("No missing values found in any column")
else:
  print(missing_with_data)

print(f"\nTotal missing values: {df.isna().sum().sum()}")

missing Values Analysis
----------------------------------------
                     Missing Count  Missing %
Product Base Margin             63       0.75

Total missing values: 63

### 2.5 — Duplicate Rows

#####Checking for completely duplicate rows in the dataset. Duplicates inflate counts and totals and must be identified before cleaning.
---

In [ ]:
print("Duplicate Rows Check:")
print("-" * 40)

duplicates = df.duplicated().sum()

if duplicates == 0:
    print("No duplicate rows found.")
else:
    print(f"Duplicate rows found: {duplicates}")
    print(f"Percentage of data: {(duplicates / len(df)) * 100:.2f}%")

Duplicate Rows Check:
----------------------------------------
No duplicate rows found.

### 2.6 — Unique Values Per Column

#####Understanding how many unique values exist in each column. This helps us identify categorical columns, spot potential data entry issues, and understand the cardinality of each field.
---

In [ ]:
print("Unique Values Per Column:")
print("-" * 40)

for col in df.columns:
  print(f"{col:30} {df[col].nunique():>6} unique values")

Unique Values Per Column:
----------------------------------------
Row ID                           8399 unique values
Order ID                         5496 unique values
Order Date                       1418 unique values
Order Priority                      5 unique values
Order Quantity                     50 unique values
Sales                            8153 unique values
Discount                           16 unique values
Ship Mode                           3 unique values
Profit                           7986 unique values
Unit Price                        751 unique values
Shipping Cost                     652 unique values
Customer Name                     795 unique values
City                             1421 unique values
Zip Code                         1626 unique values
State                              48 unique values
Region                              4 unique values
Customer Segment                    4 unique values
Product Category                    3 unique values
Product Sub-Category               17 unique values
Product Name                     1263 unique values
Product Container                   7 unique values
Product Base Margin                51 unique values
Ship Date                        1450 unique values

### 2.7 — Categorical Column Breakdown

#####Inspecting the actual values inside key categorical columns. This tells us exactly what categories, segments, regions and priorities exist in the data and how frequently each appears.
---

In [ ]:
print("Categorical Column Breakdown:")
print("=" * 40)

cat_cols = ["Ship Mode", "Customer Segment", "Region",
            "Product Category", "Product Sub-Category", "Order Priority"]

for col in cat_cols:
  print(f"\n {col}:")
  print(df[col].value_counts().to_string())
  print("-"*30)

Categorical Column Breakdown:
========================================

 Ship Mode:
Ship Mode
Regular Air       6270
Delivery Truck    1146
Express Air        983
------------------------------

 Customer Segment:
Customer Segment
Corporate         3076
Home Office       2032
Consumer          1649
Small Business    1642
------------------------------

 Region:
Region
Central    2710
West       1956
East       1895
South      1838
------------------------------

 Product Category:
Product Category
Office Supplies    4610
Technology         2065
Furniture          1724
------------------------------

 Product Sub-Category:
Product Sub-Category
Paper                             1225
Binders and Binder Accessories     915
Telephones and Communication       883
Office Furnishings                 788
Computer Peripherals               758
Pens & Art Supplies                633
Storage & Organization             546
Appliances                         434
Chairs & Chairmats                 386
Tables                             361
Office Machines                    337
Labels                             288
Envelopes                          246
Bookcases                          189
Rubber Bands                       179
Scissors, Rulers and Trimmers      144
Copiers and Fax                     87
------------------------------

 Order Priority:
Order Priority
High             1768
Low              1720
Not Specified    1672
Medium           1631
Critical         1608
------------------------------

###  2.8 — Date Range

#####Understanding the time period covered by the dataset. We check the earliest and latest order dates and confirm which years are included.
---

In [ ]:
print("Date Range Analysis:")
print("-" * 40)

df['Order date'] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

earliest = df["Order Date"].min()
latest = df["Order Date"].max()

years = sorted(df['Order Date'].dt.year.unique())
date_range_days = (latest - earliest).days

print(f"Earliest Order  : {earliest.strftime('%B %d, %Y')}")
print(f"Latest Order    : {latest.strftime('%B %d, %Y')}")
print(f"Total Date Span : {date_range_days} days ({date_range_days//365} years)")
print(f"Years Covered   : {years}")

Date Range Analysis:
----------------------------------------
Earliest Order  : January 01, 2009
Latest Order    : December 30, 2012
Total Date Span : 1459 days (3 years)
Years Covered   : [np.int32(2009), np.int32(2010), np.int32(2011), np.int32(2012)]

### 2.9 — Financial Overview

#####A high level summary of the key financial figures in the dataset. This gives us our first glimpse of the business performance before any deep analysis begins.
---

In [ ]:
print("Financial Overview:")
print("=" * 40)

total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
profit_margin = (total_profit / total_sales) * 100
avg_discount = df["Discount"].mean() * 100
max_discount = df["Discount"].max() * 100
min_profit = df["Profit"].min()
max_profit = df["Profit"].max()
avg_shipping = df["Shipping Cost"].mean()
unique_customers = df["Customer Name"].nunique()
total_orders = df["Order ID"].nunique()

print(f"Total Sales          : ${total_sales:>12,.2f}")
print(f"Total Profit         : ${total_profit:>12,.2f}")
print(f"Profit Margin        : {profit_margin:>11.2f}%")
print(f"Avg Discount         : {avg_discount:>11.1f}%")
print(f"Max Discount         : {max_discount:>11.1f}%")
print(f"Min Profit (loss)    : ${min_profit:>12,.2f}")
print(f"Max Profit           : ${max_profit:>12,.2f}")
print(f"Avg Shipping Cost    : ${avg_shipping:>12,.2f}")
print(f"Unique Customers     : {unique_customers:>12,}")
print(f"Total Unique Orders  : {total_orders:>12,}")

Financial Overview:
========================================
Total Sales          : $14,915,600.82
Total Profit         : $1,521,767.96
Profit Margin        :       10.20%
Avg Discount         :         5.0%
Max Discount         :        25.0%
Min Profit (loss)    : $  -14,140.70
Max Profit           : $   27,220.69
Avg Shipping Cost    : $       12.84
Unique Customers     :          795
Total Unique Orders  :        5,496


###  2.10 — Key Observations

After inspecting the dataset the following was found:

| Finding | Detail |
|---|---|
| Total Rows | 8,399 |
| Total Columns | 23 |
| Duplicate Rows | 0 — no action needed |
| Missing Values | 63 — need to identify which columns |
| Date Range | January 01, 2009 to December 30, 2012 |
| Years Covered | 2009 to 2012 |
| Total Sales | 14,915,600.82 |
| Total Profit | 1,521,767.96 |
| Profit Margin | 10.20% |
| Unique Customers | 5,496 |

**Issues to fix in Data Cleaning notebook:**
- Investigate and handle 63 missing values
- Confirm date range and years covered
- Fix data types — Order Date and Ship Date must be datetime
- Standardize column names to lowercase with underscores
- Check for negative profit values and document them

---
> **Next:** `02_data_cleaning.ipynb`